name: sakhi
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <3.0.2'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  uuid: ^3.0.7
  flutter_riverpod: ^2.3.6
  image_picker: ^1.0.1
  location: ^5.0.1
  http: ^0.13.6
  google_maps_flutter: ^2.3.0
  path: ^1.8.2
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  flutter_local_notifications: ^12.0.4
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  intl: ^0.18.0
  dash_chat_2: ^0.0.19
  timezone: ^0.9.4
  flutter_gemini: ^2.0.3
  url_launcher: ^6.1.11
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^3.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/initialimage.png
    - lib/assets/findway.png
    - lib/assets/medicine.png
    - lib/assets/appointment.png
    - lib/assets/male_image.png
    - lib/assets/female_image.png
    - lib/assets/lgbt.png
    - lib/assets/chat-image.png
    - lib/assets/people.png
    - lib/assets/sos.png
    - lib/assets/faq.png
    - lib/l10n/de.json
    - lib/l10n/en.json
